/**
 * Array of patterns to detect when a user is trying to contact someone
 * Used for natural language understanding in the chat component
 */
export const contactPatterns = [
  "contacto",
  "contactar",
  "cómo contactar",
  "como contactar",
  "quiero contactar",
  "ponerse en contacto",
  "comunicarse",
  "comunicarme",
  "hablar con",
  "mensaje a",
  "escribir a",
  "enviar mensaje",
  "atención al cliente",
  "servicio al cliente",
  "soporte técnico",
  "asistencia técnica",
  "chat en vivo",
  "chat en directo",
  "chat online",
  "contacto rápido",
  "contacto directo",
  "departamento comercial",
  "equipo de soporte",
  "línea de atención",
  "canal oficial",
  "contacto empresarial",
  "centro de contacto",
  "establecer contacto",
  "ponerse en contacto",
  "tomar contacto",
  "entablar comunicación",
  "entablar conversación",
  "mantener correspondencia",
  "email",
  "correo",
  "teléfono",
  "llamar",
  "whatsapp",
  "telegram",
  "redes sociales",
  "conectar",
  "propietario",
  "dueño",
  "administrador",
  "webmaster",
  "responsable",
  "encargado",
  "gerente",
  "oficina virtual",
  "horario de atención",
  "sede",
  "ubicación",
  "dirección",
  "mesa de ayuda",
  "línea directa",
  "centro de ayuda",
  "asesoría",
  "reclamación",
  "ticket",
  "representante",
  "agente",
  "operador",
  "asesor",
  "buzón",
  "helpdesk",
  "customer service",
  "canales de comunicación",
  "delegación",
  "sucursal",
  "oficina central",
  "matriz",
  "filial",
  "horarios comerciales",
  "cita previa",
  "cotización",
  "información comercial",
  "reunión virtual",
  "videollamada",
  "call center",
  "contacto urgente",
  "mensajería instantánea",
  "dirigirse a",
  "entrar en relación",
  "dirigir la palabra",
  "mario",
  "hablar con mario",
  "contactar con mario",
  "quiero hablar",
  "necesito hablar",
  "consulta",
  "pregunta",
  "duda",
  "información",
  "info",
  "ayuda",
  "soporte",
]
