console.log('🔍 Test del Motor SEO Propio')
console.log('')
console.log('📱 Para verificar el SEO implementado:')
console.log('')
console.log('1. Visita la página de test:')
console.log('   http://localhost:3000/seo-test')
console.log('')
console.log('2. Verifica los meta tags en el código fuente:')
console.log('   - Abre las herramientas de desarrollador (F12)')
console.log('   - Ve a la pestaña "Elements"')
console.log('   - Busca en <head> los siguientes tags:')
console.log('')
console.log('✅ Meta tags a verificar:')
console.log('   - <title>Test SEO | Motor SEO Propio - Mario Verdú</title>')
console.log('   - <meta name="description" content="...">')
console.log('   - <meta name="keywords" content="...">')
console.log('   - <meta property="og:title" content="...">')
console.log('   - <meta property="og:description" content="...">')
console.log('   - <meta property="og:image" content="...">')
console.log('   - <meta name="twitter:card" content="summary_large_image">')
console.log('   - <meta name="twitter:title" content="...">')
console.log('   - <link rel="canonical" href="...">')
console.log('')
console.log('3. Verifica el Schema.org JSON-LD:')
console.log('   - Busca <script type="application/ld+json">')
console.log('   - Debe contener datos estructurados de Person y WebSite')
console.log('')
console.log('4. Verifica el sitemap:')
console.log('   - Visita: http://localhost:3000/sitemap.xml')
console.log('   - Debe mostrar las URLs del sitio')
console.log('')
console.log('5. Verifica robots.txt:')
console.log('   - Visita: http://localhost:3000/robots.txt')
console.log('   - Debe mostrar las reglas de robots')
console.log('')
console.log('🎯 URLs para testear:')
console.log('   - Home: http://localhost:3000/')
console.log('   - Work Experience: http://localhost:3000/work-experience')
console.log('   - Posts: http://localhost:3000/posts')
console.log('   - SEO Test: http://localhost:3000/seo-test')
console.log('')
console.log('🔧 Herramientas de verificación:')
console.log('   - Google Rich Results Test: https://search.google.com/test/rich-results')
console.log('   - Facebook Sharing Debugger: https://developers.facebook.com/tools/debug/')
console.log('   - Twitter Card Validator: https://cards-dev.twitter.com/validator')
console.log('   - Google Search Console: https://search.google.com/search-console')
console.log('')
console.log('📊 Próximos pasos para SEO completo:')
console.log('1. Configurar Google Search Console')
console.log('2. Crear imágenes OG optimizadas (1200x630px)')
console.log('3. Implementar Google Analytics 4')
console.log('4. Optimizar Core Web Vitals')
console.log('5. Crear contenido SEO-friendly')
console.log('6. Configurar Google My Business')
console.log('7. Implementar breadcrumbs en todas las páginas')
console.log('8. Optimizar imágenes con alt text')
console.log('9. Implementar lazy loading')
console.log('10. Configurar compresión y caché')
